# Generated by Django 6.0.2 on 2026-02-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('contact_type', models.CharField(choices=[('supplier', 'مورد'), ('client', 'عميل')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية المتاحة (كيلو)')),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر شراء الكيلو')),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر بيع الكيلو')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('transaction_type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الوزن')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للكيلو')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.contact', verbose_name='التاجر/المورد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='تم التسديد؟')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.dailytransaction')),
            ],
        ),
    ]
