# Generated by Django 6.0.2 on 2026-02-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'التاجر', 'verbose_name_plural': 'التجار'},
        ),
        migrations.AlterModelOptions(
            name='dailytransaction',
            options={'verbose_name': 'حركة يومية', 'verbose_name_plural': 'اليومية (وارد وصادر)'},
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'verbose_name': 'السجل المالي', 'verbose_name_plural': 'المبالغ المستحقة (لينا وعلينا)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المخزن', 'verbose_name_plural': 'المخازن'},
        ),
        migrations.RenameField(
            model_name='financialrecord',
            old_name='status',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التاجر'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.contact', verbose_name='اسم التاجر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='السعر المستحق الكلى'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=3, verbose_name='النوع (وارد/صادر)'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.dailytransaction', verbose_name='الحركة المرتبطة'),
        ),
    ]
