# Generated by Django 5.1.2 on 2026-02-07 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('loan_type', models.CharField(default='قرض عادي', max_length=100, verbose_name='نوع القرض')),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي مبلغ القرض (الأصل)')),
                ('interest_rate_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الفائدة (%)')),
                ('loan_period_months', models.IntegerField(verbose_name='مدة القرض (بالشهور)')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية القرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='قرض نشط')),
            ],
            options={
                'verbose_name': 'قرض بنكي',
                'verbose_name_plural': 'قروض البنك',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'التاجر', 'verbose_name_plural': 'التجار'},
        ),
        migrations.AlterModelOptions(
            name='dailytransaction',
            options={'verbose_name': 'حركة يومية', 'verbose_name_plural': 'اليومية (وارد وصادر)'},
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'verbose_name': 'السجل المالي', 'verbose_name_plural': 'المبالغ المستحقة (لينا وعلينا)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المخزن', 'verbose_name_plural': 'المخازن'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='financialrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التليفون'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التاجر'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.contact', verbose_name='اسم التاجر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='السعر المستحق الكلى'),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=3, verbose_name='النوع (وارد/صادر)'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.dailytransaction', verbose_name='الحركة المرتبطة'),
        ),
        migrations.CreateModel(
            name='BankInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاريخ استحقاق القسط')),
                ('total_installment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي القسط الشهرى')),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الفائدة')),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='أصل المبلغ')),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مصاريف إضافية')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('actual_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='store.bankloan', verbose_name='القرض المرتبط')),
            ],
            options={
                'verbose_name': 'قسط بنكي',
                'verbose_name_plural': 'جدول أقساط البنك',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الدفعة')),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات (مثل: طريقة الدفع)')),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='store.financialrecord', verbose_name='السجل المالي')),
            ],
            options={
                'verbose_name': 'دفعة سداد',
                'verbose_name_plural': 'سجل الدفعات التفصيلي',
                'ordering': ['-date_paid'],
            },
        ),
    ]
