# Generated by Django 5.1.2 on 2026-02-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bankloan_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='رأس المال النقدي المتاح (الخزنة)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إدارة رأس المال',
                'verbose_name_plural': 'إدارة رأس المال',
            },
        ),
    ]
