# Generated by Django 5.1.2 on 2026-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytransaction',
            name='paid_amount_now',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع الآن'),
        ),
    ]
