# Generated by Django 5.1.2 on 2026-02-08 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_dailytransaction_paid_amount_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان (وصف المصروف)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
            ],
            options={
                'verbose_name': 'مصروف بيت',
                'verbose_name_plural': 'مصاريف البيت',
                'ordering': ['-date'],
            },
        ),
    ]
