# Generated by Django 5.1.2 on 2026-02-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_contact_id_alter_dailytransaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الدفعة')),
                ('date_paid', models.DateField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='store.financialrecord', verbose_name='السجل المالي')),
            ],
            options={
                'verbose_name': 'دفعة سداد',
                'verbose_name_plural': 'أقساط السداد',
            },
        ),
    ]
