# Generated by Django 5.1.2 on 2026-02-10 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_homeexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payer_type', models.CharField(choices=[('us', 'نحن سددنا'), ('them', 'هو سدد')], max_length=5, verbose_name='جهة السداد')),
                ('notes', models.TextField(verbose_name='بيان المصروف (نقل/عمالة/..)')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='store.contact', verbose_name='التاجر')),
            ],
            options={
                'verbose_name': 'مصروف تاجر',
                'verbose_name_plural': 'مصاريف التجار والخدمات',
                'ordering': ['-date'],
            },
        ),
    ]
