# Generated by Django 5.1.2 on 2026-02-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_financialrecord_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'التاجر', 'verbose_name_plural': '5. التجار (بيانات أساسية)'},
        ),
        migrations.AlterModelOptions(
            name='dailytransaction',
            options={'verbose_name': 'حركة يومية', 'verbose_name_plural': '1. اليومية (إضافة صادر ووارد)'},
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'verbose_name': 'السجل المالي', 'verbose_name_plural': '2. المبالغ المستحقة (لينا وعلينا)'},
        ),
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'verbose_name': 'دفعة سداد', 'verbose_name_plural': '3. أقساط وسداد المبالغ'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المخزن', 'verbose_name_plural': '4. المخازن (الأصناف)'},
        ),
    ]
