# Generated by Django 5.1.2 on 2026-02-11 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contactexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('source', models.CharField(max_length=255, verbose_name='المصدر (من أين؟)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الوارد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مبلغ وارد (دخل)',
                'verbose_name_plural': 'سجل المبالغ الواردة',
                'ordering': ['-date'],
            },
        ),
    ]
