# Generated by Django 5.1.2 on 2026-02-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_contact_options_alter_dailytransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'التاجر', 'verbose_name_plural': 'التجار'},
        ),
        migrations.AlterModelOptions(
            name='dailytransaction',
            options={'verbose_name': 'حركة يومية', 'verbose_name_plural': 'اليومية (وارد وصادر)'},
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'verbose_name': 'السجل المالي', 'verbose_name_plural': 'المبالغ المستحقة (لينا وعلينا)'},
        ),
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'verbose_name': 'دفعة سداد', 'verbose_name_plural': 'أقساط السداد'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المخزن', 'verbose_name_plural': 'المخازن'},
        ),
    ]
