# Generated by Django 5.1.2 on 2026-02-11 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_incomerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع'),
        ),
    ]
