# Generated by Django 5.1.2 on 2026-02-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_contact_options_alter_dailytransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('loan_type', models.CharField(default='قرض عادي', max_length=100, verbose_name='نوع القرض')),
                ('total_loan_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي مبلغ القرض')),
                ('loan_period_months', models.IntegerField(verbose_name='مدة القرض (بالشهور)')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية القرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='قرض نشط')),
            ],
            options={
                'verbose_name': 'قرض بنكي',
                'verbose_name_plural': 'قروض البنك',
            },
        ),
        migrations.CreateModel(
            name='BankInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='تاريخ استحقاق القسط')),
                ('total_installment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي القسط الشهرى')),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الفائدة')),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='أصل المبلغ')),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مصاريف إضافية')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('actual_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='store.bankloan', verbose_name='القرض المرتبط')),
            ],
            options={
                'verbose_name': 'قسط بنكي',
                'verbose_name_plural': 'جدول أقساط البنك',
                'ordering': ['due_date'],
            },
        ),
    ]
