# Generated by Django 5.1.2 on 2026-02-11 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_paymentinstallment_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحديث'),
        ),
    ]
