# Generated by Django 5.1.2 on 2026-02-11 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_capital_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='date',
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الدفع'),
        ),
    ]
