# Generated by Django 5.1.2 on 2026-02-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_bankinstallment_id_alter_bankloan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankloan',
            name='interest_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الفائدة (%)'),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='total_loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='إجمالي مبلغ القرض (الأصل)'),
        ),
    ]
