# Generated by Django 5.1.2 on 2026-02-11 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_capital_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع'),
        ),
    ]
