# Generated by Django 5.1.2 on 2026-02-07 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_bankloan_interest_rate_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'ordering': ['-date_paid'], 'verbose_name': 'دفعة سداد', 'verbose_name_plural': 'سجل الدفعات التفصيلي'},
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الدفع'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات (مثل: طريقة الدفع)'),
        ),
    ]
